// Shared visual tokens + list-row styles for User Center.
// Matches Home.tsx tokens exactly so the overlay feels native.

export const GOLD = "#f5b51b";
export const GOLD_LIGHT = "#ffd45a";
export const BG = "#050505";
export const CARD = "#101010";
export const BORDER = "#2a2110";

export const s = {
  overlay: {
    position: "fixed" as const,
    inset: 0,
    zIndex: 70,
    background: BG,
    display: "flex",
    flexDirection: "column" as const,
    animation: "ceoFadeIn 0.18s ease-out forwards",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "12px 14px",
    paddingTop: "calc(12px + env(safe-area-inset-top))",
    borderBottom: "1px solid #1a1a1a",
    flexShrink: 0,
  },
  headerTitle: {
    margin: 0,
    fontSize: 17,
    fontWeight: 700,
    color: "#f5f5f5",
    textAlign: "center" as const,
    flex: 1,
  },
  headerBtn: {
    width: 40,
    height: 40,
    border: 0,
    borderRadius: 12,
    background: "transparent",
    color: GOLD,
    display: "grid",
    placeItems: "center",
    cursor: "pointer",
  },
  body: {
    flex: 1,
    overflowY: "auto" as const,
    padding: "0 14px calc(24px + env(safe-area-inset-bottom))",
    WebkitOverflowScrolling: "touch" as const,
  },
  profileBlock: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "18px 4px 16px",
  },
  avatarWrap: {
    position: "relative" as const,
    width: 64,
    height: 64,
    flexShrink: 0,
  },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: "50%",
    objectFit: "cover" as const,
    border: `2px solid ${GOLD}`,
    background: "#1a1a1a",
  },
  avatarPlaceholder: {
    width: 64,
    height: 64,
    borderRadius: "50%",
    border: `2px solid ${GOLD}`,
    background: "linear-gradient(135deg,#1a1508,#0d0d0d)",
    display: "grid",
    placeItems: "center",
    color: GOLD,
    fontWeight: 800,
    fontSize: 20,
  },
  cameraBadge: {
    position: "absolute" as const,
    right: -2,
    bottom: -2,
    width: 24,
    height: 24,
    borderRadius: "50%",
    background: "#0a0a0a",
    border: `1.5px solid ${GOLD}`,
    display: "grid",
    placeItems: "center",
    color: GOLD,
    cursor: "pointer",
  },
  profileMeta: { flex: 1, minWidth: 0 },
  profileEmail: {
    fontSize: 15,
    fontWeight: 700,
    color: "#fff",
    marginBottom: 4,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  securityRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    color: "#aaa",
    marginBottom: 6,
  },
  securityHigh: { color: "#39d98a", fontWeight: 700 },
  sitePill: {
    display: "inline-block",
    padding: "3px 8px",
    borderRadius: 99,
    background: "#1a1508",
    border: `1px solid ${BORDER}`,
    color: GOLD_LIGHT,
    fontSize: 10,
    fontWeight: 600,
  },
  tabs: {
    display: "flex",
    gap: 0,
    borderBottom: "1px solid #1e1e1e",
    marginBottom: 12,
    overflowX: "auto" as const,
  },
  tab: {
    flex: 1,
    border: 0,
    background: "transparent",
    color: "#777",
    padding: "12px 6px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    position: "relative" as const,
    whiteSpace: "nowrap" as const,
  },
  tabActive: {
    color: GOLD_LIGHT,
  },
  tabUnderline: {
    position: "absolute" as const,
    left: "20%",
    right: "20%",
    bottom: 0,
    height: 2,
    background: GOLD,
    borderRadius: 2,
  },
  section: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 8,
    marginBottom: 16,
  },
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    width: "100%",
    minHeight: 52,
    padding: "12px 14px",
    border: 0,
    borderRadius: 14,
    background: CARD,
    color: "#ddd",
    textAlign: "left" as const,
    cursor: "pointer",
  },
  rowIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    background: "#17130a",
    border: `1px solid ${BORDER}`,
    display: "grid",
    placeItems: "center",
    color: GOLD,
    flexShrink: 0,
  },
  rowLabel: {
    flex: 1,
    fontSize: 14,
    fontWeight: 600,
    color: "#eee",
  },
  rowValue: {
    fontSize: 13,
    color: "#888",
    maxWidth: "42%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    textAlign: "right" as const,
  },
  rowChevron: {
    color: "#555",
    flexShrink: 0,
  },
  logoutBtn: {
    width: "100%",
    marginTop: 8,
    marginBottom: 12,
    minHeight: 48,
    border: `1px solid ${BORDER}`,
    borderRadius: 999,
    background: "transparent",
    color: GOLD_LIGHT,
    fontWeight: 700,
    fontSize: 15,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    cursor: "pointer",
  },
  toast: {
    position: "fixed" as const,
    left: "50%",
    bottom: 40,
    transform: "translateX(-50%)",
    zIndex: 100,
    width: "min(92%, 420px)",
    background: "#171717",
    border: `1px solid #5e4511`,
    color: "#eee",
    borderRadius: 12,
    padding: "12px 14px",
    boxShadow: "0 12px 30px rgba(0,0,0,.5)",
    fontSize: 13,
  },
  // Sub-screen common
  subBody: {
    flex: 1,
    overflowY: "auto" as const,
    padding: "16px 14px calc(24px + env(safe-area-inset-bottom))",
  },
  field: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 7,
    margin: "0 0 14px",
    color: "#aaa",
    fontSize: 12,
  },
  input: {
    width: "100%",
    minHeight: 48,
    border: `1px solid ${BORDER}`,
    borderRadius: 12,
    outline: 0,
    background: "#101010",
    color: "#fff",
    padding: "12px 14px",
    fontSize: 15,
  },
  primaryBtn: {
    width: "100%",
    minHeight: 48,
    border: 0,
    borderRadius: 12,
    padding: "13px 16px",
    background: `linear-gradient(135deg,${GOLD},#d98e00)`,
    color: "#090909",
    fontWeight: 800,
    fontSize: 15,
    cursor: "pointer",
    marginTop: 8,
  },
  secondaryBtn: {
    width: "100%",
    minHeight: 46,
    border: `1px solid #725316`,
    borderRadius: 12,
    padding: "11px 14px",
    background: "transparent",
    color: GOLD_LIGHT,
    fontWeight: 700,
    fontSize: 14,
    cursor: "pointer",
    marginTop: 8,
  },
  errorBox: {
    display: "flex",
    gap: 9,
    alignItems: "flex-start",
    border: "1px solid #4c2025",
    background: "#1d0c0e",
    color: "#ff9aa3",
    borderRadius: 12,
    padding: 12,
    fontSize: 13,
    lineHeight: 1.45,
    margin: "10px 0",
  },
  infoBox: {
    display: "flex",
    gap: 8,
    alignItems: "flex-start",
    border: `1px solid ${BORDER}`,
    background: "#121108",
    color: "#c5b98d",
    borderRadius: 11,
    padding: 12,
    fontSize: 12,
    lineHeight: 1.45,
    margin: "8px 0 14px",
  },
  statusPill: {
    display: "inline-block",
    padding: "3px 9px",
    borderRadius: 99,
    fontSize: 11,
    fontWeight: 700,
  },
  toggle: {
    width: 46,
    height: 28,
    borderRadius: 99,
    border: 0,
    position: "relative" as const,
    cursor: "pointer",
    transition: "background 0.2s",
    flexShrink: 0,
  },
  toggleKnob: {
    position: "absolute" as const,
    top: 3,
    width: 22,
    height: 22,
    borderRadius: "50%",
    background: "#fff",
    transition: "left 0.2s",
  },
};
